import React from "react";

function Head() {
  return (
    <>
      <title>Next.js 12| Blog</title>
      <meta name="description " content="generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </>
  );
}
export default Head;
